apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-krak8s-serviceaccount"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-krak8s-role-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-krak8s-serviceaccount"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-krak8s-clusterrole-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-krak8s-serviceaccount"
    namespace: "{{ .Release.Namespace }}"