apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-krak8s"
  labels:
    app: "{{ .Release.Name }}-krak8s"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  selector:
    app: "{{ .Release.Name }}-krak8s"

